/*
 * generated by Xtext 2.30.0
 */
package com.intuit.dsl.flow.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.intuit.dsl.flow.FlowRuntimeModule;
import com.intuit.dsl.flow.FlowStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FlowIdeSetup extends FlowStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FlowRuntimeModule(), new FlowIdeModule()));
	}
	
}
