/*
 * generated by Xtext 2.30.0
 */
package com.intuit.dsl.flow.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FlowUiModule extends AbstractFlowUiModule {

	public FlowUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
