/*
 * generated by Xtext 2.30.0
 */
package com.intuit.dsl.flow.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class FlowWebModule extends AbstractFlowWebModule {
}
