/*
 * generated by Xtext 2.30.0
 */
package com.intuit.dsl.flow;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FlowStandaloneSetup extends FlowStandaloneSetupGenerated {

	public static void doSetup() {
		new FlowStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
